name: package-store-front

on:
  push:
    paths:
      - 'src/store-front/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
    
jobs:
  publish-container-image:
    
    runs-on: ubuntu-latest

    steps:
      - name: Set environment variables
        id: set-variables
        run: |
          echo "REPOSITORY=ghcr.io/$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')/$(echo ${{ github.ref_name }} | tr '[:upper:]' '[:lower:]')" >> "$GITHUB_OUTPUT"
          echo "IMAGE=store-front" >> "$GITHUB_OUTPUT"
          echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"
          echo "CREATED=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.REPOSITORY }}
          echo ${{ steps.set-variables.outputs.IMAGE }}
          echo ${{ steps.set-variables.outputs.VERSION }}
          echo ${{ steps.set-variables.outputs.CREATED }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: preset values
        run: |
          sudo snap install yq
          yq -i '.storeFront.image.tag = "f1e66df"' charts/aks-store-demo/values.yaml
          # Note: the following account information will not work on GHES
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add .
          git commit -m "version bump"
          git push

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}       
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: src/store-front
          file: src/store-front/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:latest
            ${{ steps.set-variables.outputs.REPOSITORY }}/${{ steps.set-variables.outputs.IMAGE }}:${{ steps.set-variables.outputs.VERSION }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.created=${{ steps.set-variables.outputs.CREATED }}
            org.opencontainers.image.revision=${{ steps.set-variables.outputs.VERSION }}
  version-chart:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    needs: publish-container-image
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set environment variables
        id: set-variables
        run: |
          echo "VERSION=$(echo ${GITHUB_SHA} | cut -c1-7)" >> "$GITHUB_OUTPUT"

      - name: Env variable output
        id: test-variables
        run: |
          echo ${{ steps.set-variables.outputs.VERSION }}
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Commit version bump
        run: |
          yq -i '.storeFront.image.tag = "${{ steps.set-variables.outputs.VERSION }}"' charts/aks-store-demo/values.yaml
          # Note: the following account information will not work on GHES
          git config user.name "actions-user"
          git config user.email "actions@github.com"
          git add .
          git commit -m "version bump"
          git push